version: "3.8"

services:

  redis:
    container_name: redis
    image: redis:7.0.11-alpine
    restart: always
    networks:
      - main

  db:
    container_name: db
    image: postgres:14.2
    restart: always
    networks:
      - main
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env

  backend:
    container_name: app
    build: .
    command: sh -c "gunicorn --config gunicorn_config.py kernel.wsgi:application"
    volumes:
      - .:/usr/src/app/
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/media
      - /etc/letsencrypt:/etc/letsencrypt/:ro
    expose:
      - "8000"
    env_file:
      - ./.env
    networks:
      - main
    depends_on:
      - db
  s3:
    container_name: minio
    image: quay.io/minio/minio:RELEASE.2024-12-18T13-15-44Z
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - main
    volumes:
      - 'minio_data:/data'
    env_file:
      - ./.env
    command: minio server /data --console-address ":9001" --address ":9000"
  celery:
    container_name: celery
    build: .
    command: celery -A kernel worker -l INFO
    volumes:
      - .:/usr/src/app/
      - /etc/letsencrypt:/etc/letsencrypt/:ro
      - media_volume:/usr/src/app/media
      - static_volume:/usr/src/app/staticfiles
    env_file:
      - ./.env
    networks:
      - main
    depends_on:
      - redis
      - backend

  frontend:
     build:
       context: ../front
     volumes:
       - react_build:/front/dist

  nginx:
     container_name: nginx
     image: nginx:alpine
     restart: unless-stopped
     ports:
       - "80:80"
       - "443:443"
     volumes:
       - ./nginx/conf.d/:/etc/nginx/conf.d/
       - /etc/letsencrypt:/etc/letsencrypt/:ro
       - media_volume:/usr/src/app/media
       - static_volume:/usr/src/app/staticfiles
       - react_build:/var/www/dist
     depends_on:
       - backend
       - frontend
     networks:
       - main

networks:
  main:

volumes:
  postgres_data:
  static_volume:
  media_volume:
  react_build:
  minio_data:
