version: '3.9'

services:

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_
    command:
      - --storage.tsdb.retention.time=7d
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - main
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9090" ]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"


  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - main

  flower:
    image: mher/flower
    ports:
      - 5555:5555
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672/
    networks:
      - main

  db:
    container_name: db
    image: postgres:14.2
    restart: always
    networks:
      - main
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - main

  redis:
    container_name: redis
    image: redis:7.0.11-alpine
    restart: always
    networks:
      - main


  backend:
    container_name: app
    build: .
    command: sh -c "gunicorn --config gunicorn_config.py kernel.wsgi:application"
    volumes:
      - .:/usr/src/app/
      - /var/www/static/:/var/www/static/
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/media
      - /etc/letsencrypt:/etc/letsencrypt/:ro
    expose:
      - "8000"
    env_file:
      - ./.env
    networks:
      - main
    depends_on:
      - redis
      - db
      - prometheus


  celery:
    container_name: celery
    build: .
    command: celery -A kernel worker -l INFO -Q email,git  -E
    volumes:
      - .:/usr/src/app/
      - /var/www/static/:/var/www/static/
      - /etc/letsencrypt:/etc/letsencrypt/:ro
      - media_volume:/usr/src/app/media
      - static_volume:/usr/src/app/staticfiles
    env_file:
      - ./.env
    networks:
      - main
    depends_on:
      - redis
      - backend
      - rabbitmq
  frontend:
    build:
      context: ../front
    volumes:
      - react_build:/front/build

  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - /var/www/static/:/var/www/static/
      - /etc/letsencrypt:/etc/letsencrypt/:ro
      - media_volume:/usr/src/app/media
      - static_volume:/usr/src/app/staticfiles
      - react_build:/var/www/front
    depends_on:
      - backend
      - frontend
    networks:
      - main



networks:
  main:

volumes:
  postgres_data:
  static_volume:
  media_volume:
  react_build: