global:
  scrape_interval: 15s # when Prometheus is pulling data from exporters etc
  evaluation_interval: 30s # time between each evaluation of Prometheus' alerting rules , The default is every 1 minute.

scrape_configs:
  - job_name: app   # your project name
    static_configs:
      - targets:
        - app:8000
