# Generated by Django 5.0.2 on 2024-07-31 15:11

import django.core.validators
import django.db.models.deletion
import volunteer.models.task
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Title')),
                ('color', models.CharField(blank=True, max_length=200, null=True, verbose_name='Color')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
            ],
            options={
                'verbose_name': 'موقعیت ',
                'verbose_name_plural': 'موقعیت ها',
            },
        ),
        migrations.CreateModel(
            name='TaskTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.PositiveIntegerField(default=0, verbose_name='ساعت')),
                ('days', models.PositiveIntegerField(default=0, verbose_name='روز')),
            ],
        ),
        migrations.CreateModel(
            name='CourseVolunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('key', models.CharField(max_length=200, verbose_name='key')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('color', models.CharField(blank=True, max_length=200, null=True, verbose_name='Color')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Order')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.state', verbose_name='State')),
            ],
            options={
                'verbose_name': 'وضعیت ',
                'verbose_name_plural': 'وضعیت ها',
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='نام')),
                ('last_name', models.CharField(max_length=300, verbose_name='نام خانوادگی')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ایمیل')),
                ('phone_number', models.CharField(max_length=11, verbose_name='نلفن')),
                ('year_of_birth', models.PositiveIntegerField(verbose_name='سال تولد')),
                ('url_github', models.URLField(blank=True, null=True, verbose_name='آدرس گیت هاب')),
                ('url_linkedin', models.URLField(verbose_name='ادرس لینکدین')),
                ('register_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت نام')),
                ('is_special', models.BooleanField(default=False, verbose_name='ویژه')),
                ('course', models.ManyToManyField(blank=True, null=True, through='volunteer.CourseVolunteer', to='course.course')),
                ('state', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='volunteers', to='volunteer.state', verbose_name='مرحله')),
                ('status', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.DO_NOTHING, to='volunteer.status', verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'داوطلب',
                'verbose_name_plural': 'داوطلب ها',
                'ordering': ('register_time',),
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=300, null=True, verbose_name='موضوع')),
                ('send_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان ارسال')),
                ('response_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان پاسخ')),
                ('file', models.FileField(null=True, upload_to=volunteer.models.task.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['rar', 'zip', 'pdf', 'JPG', 'JPEG', 'png', 'jpg', 'jpeg', 'svg', 'SVG', 'xlsx'])], verbose_name='فایل')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='volunteer.volunteer', verbose_name='داوطلب')),
            ],
            options={
                'verbose_name': 'تسک ها',
                'verbose_name_plural': 'تسک',
            },
        ),
        migrations.AddField(
            model_name='coursevolunteer',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.volunteer'),
        ),
    ]
