# Generated by Django 5.0.2 on 2024-02-24 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('color', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('color', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'وضعیت ',
                'verbose_name_plural': 'وضعیت ها',
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=11)),
                ('year_of_birth', models.PositiveIntegerField()),
                ('url_github', models.URLField(blank=True, null=True)),
                ('url_linkedin', models.URLField()),
                ('register_time', models.DateTimeField(auto_now_add=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='volunteers', to='volunteer.state')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='volunteers', to='volunteer.status')),
            ],
            options={
                'verbose_name': 'داوطلب',
                'verbose_name_plural': 'داوطلب ها',
                'ordering': ('register_time',),
            },
        ),
    ]
