# Generated by Django 5.0.2 on 2024-05-24 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Title')),
                ('color', models.CharField(blank=True, max_length=200, null=True, verbose_name='Color')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
            ],
            options={
                'verbose_name': 'موقعیت ',
                'verbose_name_plural': 'موقعیت ها',
            },
        ),
        migrations.CreateModel(
            name='CourseVolunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('key', models.CharField(max_length=200, verbose_name='key')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('color', models.CharField(blank=True, max_length=200, null=True, verbose_name='Color')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Order')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.state', verbose_name='State')),
            ],
            options={
                'verbose_name': 'وضعیت ',
                'verbose_name_plural': 'وضعیت ها',
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='First name')),
                ('last_name', models.CharField(max_length=300, verbose_name='Last name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=11, verbose_name='Phone')),
                ('year_of_birth', models.PositiveIntegerField(verbose_name='Year of birth')),
                ('url_github', models.URLField(blank=True, null=True, verbose_name='Url github')),
                ('url_linkedin', models.URLField(verbose_name='Url linkedin')),
                ('register_time', models.DateTimeField(auto_now_add=True, verbose_name='Register time')),
                ('is_send_email', models.BooleanField(default=False, verbose_name='Is send email')),
                ('course', models.ManyToManyField(blank=True, null=True, through='volunteer.CourseVolunteer', to='course.course')),
                ('state', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='volunteers', to='volunteer.state')),
                ('status', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.DO_NOTHING, to='volunteer.status')),
            ],
            options={
                'verbose_name': 'داوطلب',
                'verbose_name_plural': 'داوطلب ها',
                'ordering': ('register_time',),
            },
        ),
        migrations.AddField(
            model_name='coursevolunteer',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.volunteer'),
        ),
    ]
