# Generated by Django 5.0.2 on 2024-04-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='status',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='ترتیب:'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='ایمیل'),
        ),
    ]
