# Generated by Django 5.0.2 on 2024-05-24 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('volunteer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='روز')),
                ('start_time', models.TimeField(verbose_name='زمان شروع ')),
                ('end_time', models.TimeField(verbose_name='زمان پایان')),
                ('number_reserve', models.PositiveIntegerField(default=0, verbose_name='حد مجاز رزرو')),
            ],
            options={
                'verbose_name': 'زمان',
                'verbose_name_plural': 'زمان ها',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, max_length=300, null=True, verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('Pending', 'مصاحبه انجام نشده'), ('Accept', 'مصاحبه-پذیرفته شد'), ('Rejected', 'مصاحبه - پذیرفته نشد')], default=('Pending', 'مصاحبه انجام نشده'), max_length=10, verbose_name='وضعیت')),
                ('link_meeting', models.CharField(blank=True, max_length=4000, null=True, verbose_name='لینک جلسه')),
                ('interviewee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interviewee', to='volunteer.volunteer', verbose_name='مصاحبه شونده')),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interviewer', to=settings.AUTH_USER_MODEL, verbose_name='مصاحبه کننده')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='calender.time', verbose_name='زمان')),
            ],
            options={
                'verbose_name': 'رویداد',
                'verbose_name_plural': 'رویداد ها',
                'ordering': ('time',),
            },
        ),
    ]
