# Generated by Django 5.0.2 on 2024-02-24 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('volunteer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('number_reserve', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('result', models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=8)),
                ('interviewee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interviewee', to='volunteer.volunteer')),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interviewer', to=settings.AUTH_USER_MODEL)),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='calender.time')),
            ],
            options={
                'verbose_name': 'رویداد',
                'verbose_name_plural': 'رویداد ها',
            },
        ),
    ]
