# Generated by Django 5.0.2 on 2024-07-31 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, max_length=300, null=True, verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('Pending', 'مصاحبه انجام نشده'), ('Accept', 'تایید'), ('Rejected', 'عدم تایید')], default=('Pending', 'مصاحبه انجام نشده'), max_length=10, verbose_name='وضعیت')),
                ('link_meeting', models.CharField(blank=True, max_length=4000, null=True, verbose_name='لینک جلسه')),
            ],
            options={
                'verbose_name': 'رویداد',
                'verbose_name_plural': 'رویداد ها',
                'ordering': ('time',),
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='روز')),
                ('start_time', models.TimeField(verbose_name='زمان شروع ')),
                ('end_time', models.TimeField(verbose_name='زمان پایان')),
                ('number_reserve', models.PositiveIntegerField(default=0, verbose_name=' تعداد بار رزرو')),
            ],
            options={
                'verbose_name': 'زمان',
                'verbose_name_plural': 'زمان ها',
            },
        ),
    ]
