# Generated by Django 5.0.2 on 2024-07-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='number_reserve',
            field=models.PositiveIntegerField(default=0, verbose_name=' تعداد بار رزرو'),
        ),
    ]
