# Generated by Django 5.0.2 on 2024-04-15 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0001_initial'),
        ('volunteer', '0002_alter_state_title_alter_status_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('time',), 'verbose_name': 'رویداد', 'verbose_name_plural': 'رویداد ها'},
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='event',
            name='interviewee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interviewee', to='volunteer.volunteer', verbose_name='مصاحبه شونده'),
        ),
        migrations.AlterField(
            model_name='event',
            name='interviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interviewer', to=settings.AUTH_USER_MODEL, verbose_name='مصاحبه کننده'),
        ),
        migrations.AlterField(
            model_name='event',
            name='link_meeting',
            field=models.CharField(blank=True, max_length=4000, null=True, verbose_name='لینک جلسه'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Pending', 'مصاحبه انجام نشده'), ('Accept', 'مصاحبه-پذیرفته شد'), ('Rejected', 'مصاحبه - پذیرفته نشد')], default=('Pending', 'مصاحبه انجام نشده'), max_length=10, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='calender.time', verbose_name='زمان'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='time',
            name='day',
            field=models.DateField(verbose_name='روز'),
        ),
        migrations.AlterField(
            model_name='time',
            name='end_time',
            field=models.TimeField(verbose_name='زمان پایان'),
        ),
        migrations.AlterField(
            model_name='time',
            name='number_reserve',
            field=models.PositiveIntegerField(default=0, verbose_name='حد مجاز رزرو'),
        ),
        migrations.AlterField(
            model_name='time',
            name='start_time',
            field=models.TimeField(verbose_name='زمان شروع '),
        ),
    ]
