# Generated by Django 5.0.2 on 2024-07-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0002_alter_time_number_reserve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Pending', 'مصاحبه انجام نشده'), ('Accept', 'تایید'), ('Rejected', 'عدم تایید')], default=('Pending', 'مصاحبه انجام نشده'), max_length=10, verbose_name='وضعیت'),
        ),
    ]
